### ISSUE TITLE
Вынести подключение к БД в конфиг

### ISSUE THREAD

**Issue by MikhailovAlexander** [HSE-Perm-projects-23-24/vaccine_app-back#2]
Строка подключения к БД указана непосредственно в исходном коде, необходимо вынести ее в конфигурационный файл.
https://github.com/HSE-Perm-projects-23-24/vaccine_app-back/blob/42bccd6f9c8d9d48a4ed3ecaae65d3c398cd249d/MyVaccinesWeb/Models/ProceduresContext.cs#L44

**Comment by daria-rakovskaia** [comment]
Вынесла подключение к БД в конфиг, теперь строка подключения находится в файле "appsettings.json", также дополнительно потребовалось подключить NuGet пакет "Microsoft.Extensions.Configuration.Json"

https://github.com/HSE-Perm-projects-23-24/vaccine_app-back/commit/2f05fd78957d6a50265596fd90564fa7cb56c728

**Comment by daria-rakovskaia** [comment]
Вынесла подключение к БД в "appsettings.json", для этого также потребовалось скачать NuGet пакет "Microsoft.Extensions.Configuration.Json"
